baseURL = "https://p30emdad.ir/"
languageCode = "fa-ir"
title = "Ø§Ù…Ø¯Ø§Ø¯ Ø±Ø§ÛŒØ§Ù†Ù‡"
theme = "github-style"
# googleAnalytics = "UA-123456-789"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "p30emdad"
  description = "Ù¾Ø§Ø³Ø® Ø¨Ù‡ Ù¾Ø±Ø³Ø´â€ŒÙ‡Ø§ÛŒ ÙÙˆØ±ÛŒ Ø´Ù…Ø§ Ø¯Ø± Ø²Ù…ÛŒÙ†Ù‡â€ŒÛŒ Ú©Ø§Ù…Ù¾ÛŒÙˆØªØ±ØŒ Ù…ÙˆØ¨Ø§ÛŒÙ„ Ùˆ Ø§ÛŒÙ†ØªØ±Ù†Øª"
  # github = "tayyebi"
  # facebook = "MeiK2333"
  # twitter = "MeiK2333"
  # linkedin = "mohammadrezatayyebi"
  phone = "0 921 0 115 404"
  instagram = "tyyinet"
  tumblr = "MeiK2333"
  # email = "smile@tyyi.net"
  url = "https://p30emdad.ir/post"
  keywords = "Ø±Ø§ÛŒØ§Ù†Ù‡, Ø§Ù…Ø¯Ø§Ø¯, ÙÙˆØ±ÛŒ"
  rss = true
  lastmod = true
  userStatusEmoji = "ğŸš‘"
  favicon = "/images/github.png"
  location = "Hamedan"

  enableGitalk = false
  [params.gitalk]
    clientID = "Your client ID" 
    clientSecret = "Your client secret" 
    repo = "repo"
    owner = "MeiK2333"
    admin = "MeiK2333"
    id = "location.pathname"
    labels = "gitalk"
    perPage = 15
    pagerDirection = "last"
    createIssueManually = true
    distractionFreeMode = false

  # [[params.links]]
  #   title = "Link"
  #   href = "https://github.com/meik2333"
  # [[params.links]]
  #   title = "Link2"
  #   href = "https://meik2333.com"
  #   icon = "https://meik2333.com/images/avatar.png"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]